function addcomment(data) {
	title = data.title || 'err';
	link = data.permalink || 'err';
	let html = "";
	html += '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"' + "\n";
	html += 'integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">' + "\n";
	html += '<script src="PHP_DIR/zizai_captcha/captcha.php" type="text/javascript"></script>' + "\n";
	html += '<style>' + "\n";
	html += '#Comment_namebar {' + "\n";
	html += '    background-color: rgba(201, 167, 162, 0.486);' + "\n";
	html += '}' + "\n";
	html += '' + "\n";
	html += '#Comment_datebar {' + "\n";
	html += '    text-align: right;' + "\n";
	html += '}' + "\n";
	html += '</style>' + "\n";
	html += '<h4 name="Comment_Top">コメント</h4>' + "\n";
	html += '<div class="rounded" style="background-color: rgba(0, 50, 214, 0.096);padding: 20px;">' + "\n";
	html += '    <!--投稿欄-->' + "\n";
	html += '    <div id="accordion">' + "\n";
	html += '        <div class="card">' + "\n";
	html += '            <div class="card-header" id="commentHeader">' + "\n";
	html += '                <h5 class="mb-0">' + "\n";
	html += '                    <button class="btn btn-link" data-toggle="collapse" data-target="#CommentForm" aria-expanded="false"' + "\n";
	html += '                        aria-controls="CommentForm">' + "\n";
	html += '                        コメントを投稿する...' + "\n";
	html += '                    </button>' + "\n";
	html += '                </h5>' + "\n";
	html += '            </div>' + "\n";
	html += '            <div id="CommentForm" class="collapse" aria-labelledby="commentHeader" data-parent="#accordion">' + "\n";
	html += '                <div class="card-body">' + "\n";
	html += '                    <div class="row">' + "\n";
	html += '                        <form action="PHP_DIR/post.php" method="post" id="Comment_postform" class="needs-validation"' + "\n";
	html += '                            style="flex-shrink: 0;flex-grow: 1;" novalidate>' + "\n";
	html += '                            <div class="" style="padding-left: 20px; padding-right: 20px;">' + "\n";
	html += '                                <div class="mb-3">' + "\n";
	html += '                                    <label for="Comment_name">名前</label>' + "\n";
	html += '                                    <input type="text" class="form-control" name="Comment_name" id="Comment_name"' + "\n";
	html += '                                        placeholder="" value="" required>' + "\n";
	html += '                                    <div class="invalid-feedback">' + "\n";
	html += '                                        名前を入れてください' + "\n";
	html += '                                    </div>' + "\n";
	html += '                                </div>' + "\n";
	html += '                                <div class="mb-3">' + "\n";
	html += '                                    <label for="Comment_comment">コメント</label>' + "\n";
	html += '                                    <input type="text" class="form-control" name="Comment_comment" id="Comment_comment"' + "\n";
	html += '                                        placeholder="" value="" required>' + "\n";
	html += '                                    <div class="invalid-feedback">' + "\n";
	html += '                                        本文を入れてください' + "\n";
	html += '                                    </div>' + "\n";
	html += '                                </div>' + "\n";
	html += '                                <script>zizai_captcha_show();</script><br>' + "\n";
	html += '                                <!--ここから-->' + "\n";
	html += '                                <input type="hidden" name="Comment_page" value="PAGE_TITLE">' + "\n";
	html += '                                <input type="hidden" name="Comment_echoback" value="ECHOBACK">' + "\n";
	html += '                                <!--ここまで-->' + "\n";
	html += '                                <button class="btn btn-primary float-right" type="submit">投稿</button>' + "\n";
	html += '                            </div>' + "\n";
	html += '                        </form>' + "\n";
	html += '                    </div>' + "\n";
	html += '                </div>' + "\n";
	html += '            </div>' + "\n";
	html += '        </div>' + "\n";
	html += '    </div>' + "\n";
	html += '' + "\n";
	html += '    <!-- 表示欄-->' + "\n";
	html += '    <div style="padding-top: 20px;">' + "\n";
	html += '        <div class="border-bottom" id="comment-container">' + "\n";
	html += '            <p id="Comment_loading">コメント読み込み中...</p>' + "\n";
	html += '        </div>' + "\n";
	html += '    </div>' + "\n";
	html += '</div>' + "\n";
	html += '<script type="text/javascript">' + "\n";
	html += '    document.getElementById("Comment_postform").addEventListener(\'submit\', function () {' + "\n";
	html += '        localStorage.setItem("name", document.getElementById("Comment_name").value);' + "\n";
	html += '        localStorage.setItem("comment", document.getElementById("Comment_comment").value);' + "\n";
	html += '        localStorage.setItem("isFinished", "false");' + "\n";
	html += '    });' + "\n";
	html += '' + "\n";
	html += '    function addComment(name, comment, date) {' + "\n";
	html += '        let parent = document.createElement("div");' + "\n";
	html += '        let topcontainer = document.createElement("div");' + "\n";
	html += '        topcontainer.classList.add("row");' + "\n";
	html += '        topcontainer.id = "Comment_namebar";' + "\n";
	html += '        let named = document.createElement("div");' + "\n";
	html += '        named.classList.add("col-sm-2");' + "\n";
	html += '        let nameh = document.createElement("h6");' + "\n";
	html += '        nameh.textContent = name;' + "\n";
	html += '        named.appendChild(nameh);' + "\n";
	html += '        let dated = document.createElement("div");' + "\n";
	html += '        dated.classList.add("col-sm-10");' + "\n";
	html += '        dated.id = "Comment_datebar";' + "\n";
	html += '        dated.textContent = date;' + "\n";
	html += '        topcontainer.appendChild(named);' + "\n";
	html += '        topcontainer.appendChild(dated);' + "\n";
	html += '        parent.appendChild(topcontainer)' + "\n";
	html += '' + "\n";
	html += '        let mainc = document.createElement("p");' + "\n";
	html += '        mainc.textContent = comment;' + "\n";
	html += '        parent.appendChild(mainc);' + "\n";
	html += '' + "\n";
	html += '        document.getElementById("comment-container").appendChild(parent);' + "\n";
	html += '    }' + "\n";
	html += '' + "\n";
	html += '    window.onload = function () {' + "\n";
	html += '        var xhr = new XMLHttpRequest();' + "\n";
	html += '        //ここから' + "\n";
	html += '        xhr.open(\'GET\', \'PHP_DIR/sqljson.php?page=PAGE_TITLE\', true);' + "\n";
	html += '        //ここまで' + "\n";
	html += '        xhr.onreadystatechange = function () {' + "\n";
	html += '            if (this.readyState == 4 && this.status == 200) {' + "\n";
	html += '                if (this.response) {' + "\n";
	html += '                    let json = this.response;' + "\n";
	html += '                    for (let i in json) {' + "\n";
	html += '                        addComment(json[i].name, json[i].comment, json[i].date);' + "\n";
	html += '                    }' + "\n";
	html += '                    document.getElementById("Comment_loading").hidden = true;' + "\n";
	html += '                }' + "\n";
	html += '            }' + "\n";
	html += '        }' + "\n";
	html += '        xhr.responseType = \'json\';' + "\n";
	html += '        xhr.send(null);' + "\n";
	html += '' + "\n";
	html += '        if (localStorage.getItem("isFinished")) {' + "\n";
	html += '            if (localStorage.getItem("isFinished") == "false") {' + "\n";
	html += '                document.getElementById("Comment_name").value = localStorage.getItem("name");' + "\n";
	html += '                document.getElementById("Comment_comment").value = localStorage.getItem("comment");' + "\n";
	html += '            } else {' + "\n";
	html += '                localStorage.removeItem("name");' + "\n";
	html += '                localStorage.removeItem("comment");' + "\n";
	html += '                localStorage.removeItem("isFinished");' + "\n";
	html += '            }' + "\n";
	html += '        }' + "\n";
	html += '    }' + "\n";
	html += '</script>' + "\n";
	html += '' + "\n";
	html += '<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"' + "\n";
	html += '    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"' + "\n";
	html += '    crossorigin="anonymous"></script>' + "\n";
	html += '<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"' + "\n";
	html += '    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"' + "\n";
	html += '    crossorigin="anonymous"></script>' + "\n";
	html += '<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"' + "\n";
	html += '    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"' + "\n";
	html += '    crossorigin="anonymous"></script>' + "\n";
	html += '<script>' + "\n";
	html += '        (function () {' + "\n";
	html += '            \'use strict\';' + "\n";
	html += '            window.addEventListener(\'load\', function () {' + "\n";
	html += '                var forms = document.getElementsByClassName(\'needs-validation\');' + "\n";
	html += '                var validation = Array.prototype.filter.call(forms, function (form) {' + "\n";
	html += '                    form.addEventListener(\'submit\', function (event) {' + "\n";
	html += '                        if (form.checkValidity() === false) {' + "\n";
	html += '                            event.preventDefault();' + "\n";
	html += '                            event.stopPropagation();' + "\n";
	html += '                        }' + "\n";
	html += '                        form.classList.add(\'was-validated\');' + "\n";
	html += '                    }, false);' + "\n";
	html += '                });' + "\n";
	html += '            }, false);' + "\n";
	html += '        })();' + "\n";
	html += '</script>' + "\n";
	
	html = html.replace(/PAGE_TITLE/g, title).replace("ECHOBACK", link).replace(/PHP_DIR/g, hexo.config.phpcomment.phpdir);
	data.content += html;
	return data;
}

// _helper.register('comment', addcomment);
hexo.extend.filter.register('after_post_render', addcomment);
